// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"shopeefy/di"
	"shopeefy/internal/controller"
	"shopeefy/internal/repository"
	"shopeefy/internal/repository/dao"
	"shopeefy/internal/service"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := di.InitMiddlewares()
	shopifyApp := di.InitShopifyAppEnv()
	db := di.InitDB()
	shopDAO := dao.NewShopDAO(db)
	shopRepo := repository.NewShopRepo(shopDAO)
	shopService := service.NewShopService(shopRepo)
	authHandler := controller.NewAuthHandler(shopifyApp, shopService)
	v2 := di.InitHandler(authHandler)
	engine := di.InitWebServer(v, v2)
	return engine
}
