// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"shopeefy/di"
	"shopeefy/internal/controller"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := di.InitMiddlewares()
	shopifyApp := di.InitShopifyAppEnv()
	authHandler := controller.NewAuthHandler(shopifyApp)
	v2 := di.InitHandler(authHandler)
	engine := di.InitWebServer(v, v2)
	return engine
}
