test:
  algoshop: 12345

mysql:
  dsn: "root:root@tcp(localhost:13316)/algoshop"

redis:
  addr: "localhost:6379"

algoshop:
  client_id: "964fbe18a1f4f7aa2239dddbbac693e5"
  client_secret: "5a6be8f607a010611847610b3541f153"
  scopes: "write_products"
  redirect_uri: "https://e99a-111-4-141-249.ngrok-free.app/auth/callback"
